version: '3'
services:
    core:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        container_name: core
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1 #fix some QT bugs
            - XAUTHORITY=/tmp/.docker.xauth
            - NVIDIA_VISIBLE_DEVICES=all
            - DOCKER_HOST=unix:///run/user/1000/docker.sock
#        user: 1000:1000
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - $X11_SOCKET:$X11_SOCKET:rw
            - $XAUTH:$XAUTH
            - $WORKSPACE:/home/mushroom/catkin_ws
        working_dir: /home/mushroom/catkin_ws
networks:
  ros:
    driver: host